apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: redis
spec:
  containers:
  - image: redis
    name: redis
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    env: demo    
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
