apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  nginx-deploy
  labels:
    tier: backend
spec:
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
  replicas: 3
  selector:
    matchLabels:
      app: v1
